apiVersion: v1
kind: Service
metadata:
  name: prime-app
  labels:
    app: prime-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: prime-app
